#!/usr/bin/env bash
# This script stops the "4-to_infinity_and_beyond" process using kill.

# Find the PID of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")
# Check if the process exists
if [ -n "$pid" ]; then
    # If the process exists, kill it
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi
