#!/usr/bin/env bash
# This script displays the content of /etc/passwd with only username, user id, and home directory path for the user

while IFS=":" read -r username _ userid _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
