#!/usr/bin/env bash
# This script configures an Ubuntu server to update the IP address mappings in /etc/hosts

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root"
    exit 1
fi

# Check if an argument is provided
if [ $# -ne 0 ]; then
    echo "Usage: $0"
    exit 1
fi

# Update /etc/hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

# Display success message
echo "Configuration updated successfully"
