#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root"
    exit 1
fi
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts
echo "Configuration updated successfully"
